language: node_js
sudo: false
node_js:
  - "10"
install:
  - npm install --no-package-lock
script:
  - npm run bump-patch-version
  - git push origin master
deploy:
  provider: npm
  email: josesegurag90@gmail.com
  api_key: $NPM_TOKEN
