language: node_js
sudo: false
node_js:
  - "10"
install:
  - npm install --no-package-lock
deploy:
  provider: script
  skip_cleanup: true
  script: .travis/pu.sh
  on:
    branch: master
    tags: false
