language: node_js
sudo: false
node_js:
  - "10"
install:
  - yarn install
test:
  - yarn run test
build:
  - yarn run build
deploy:
  - provider: script
    skip_cleanup: true
    script: "sh ./scripts/pu.sh"
    on:
      branch: master
      tags: false
  - provider: npm
    email: josesegurag90@gmail.com
    api_key: NPM_TOKEN
    on:
      branch: master
      tags: false
